version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.platform:org.eclipse.debug.core"
        versions: ">= 3.17.0"
      - dependency-name: "org.eclipse.jdt:org.eclipse.jdt.launching"
        versions: ">= 3.18.0"
  - package-ecosystem: "maven"
    directory: "/src/it/test"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/webapp"
    schedule:
      interval: "daily"
