dist: trusty
language: java
jdk:
  - openjdk7
script: "mvn -s travis-settings.xml deploy"
env:
  global:
    - secure: "iqLDXndwIWO86hzAfwkKj3lno+dyzVdXANO9k7CuHnEDkvBQfbVgskJfiS8KxicqcHXaACsZZ1uhWWB4Zbdhiz5eM4nB+HULX4yAc4bUWR64skrDi8o0Ee7j76isdEl3mokpeQLJXUameEUVKC9G1R6mzV64ZXA1prNVsRa7sCuuSshG8lWzAvJIakI5v3GhO4uxLmcjIXZOSk66bO13DwiIAzBR9Fz7CHRd+Aqe/LeB0PrKluJnL6KKo/cyp8Jw/7cnnH2uIe37QCwzV8V5Xc6B+V1YG5Sa7GUaK+DoPwZ5mmmvLBEnaMNUq5x34KZ6sg7lBFcvMJsVnXgCeB1wYe/wGgJman2F6vommChX2g8ZoXKiJhfHbRbfNwEO98bI/2V6gZ2TvmFnoahyBEKna6QoASKQKo2RFdQxbf76AYPtjjRgjCVxpOZCVfXK4r3P8a2nwUOTriPds9yiv6yUAB6+c8Ko/Kep/4n1b1DwHW59/DrDu/+YVIS54Nt5cUsZl9mPZIofQsAuNZxgYJt1LYpgTZLmwNIb2RoosLx+fcbGjzQWD2LoojKSjbUQiltD4zuGVdfkrKs6eRn6rhEWMzYtBoD053KeI8eiJxtD+VB97gZQ4eL0i0oQAzIvZbFKO80iGZ1cm3I39RZGv05pDdDU60w0/MqeLAxtsleQFzA="
cache:
  directories:
  - $HOME/.m2
